# Generated by Django 5.0.1 on 2024-04-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_contact_desc_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('desc', models.TextField(max_length=122)),
            ],
        ),
    ]
